export const localMapSoundSrc = require('../../components/Audio/localMapSound.mp3')
export const fireballHit = require('../../components/Audio/fireballHit.wav')
export const initBattleSound = require('../../components/Audio/initBattle.wav')
export const initFireball = require('../../components/Audio/initFireball.wav')
export const battle = require('../../components/Audio/battle.mp3')
export const tackleHit = require('../../components/Audio/tackleHit.wav')
export const victory = require('../../components/Audio/victory.wav')
export const map = require('../../components/Audio/map.wav')